Style/BarePercentLiterals:
  Enabled: false
Style/PercentLiteralDelimiters:
  Enabled: false
Style/UnneededPercentQ:
  Enabled: false
Metrics/LineLength:
  Enabled: false
Style/SpecialGlobalVars:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
